version: '2'

services:
  rest:
    #Uncomment line below if you want to build from Github source code
    #Otherwise it will pull pre-built images from Docker Hub
    #build: ./rest
    container_name: rest
    image: appdynamics/sample-app-rest
    environment:
      - CONTROLLER_URL=peaks202002061058544.saas.appdynamics.com
      - CONTROLLER_PORT=443
      - CONTROLLER_ACCOUNT_NAME=peaks202002061058544
      - CONTROLLER_ACCESS_KEY=t84drcmx46cv
      - PORTAL_USERNAME=sihili6330
      - PORTAL_PASSWORD=appdynamics
      - AGENT_VERSION=4.5.16.2252
    links:
      - db
    ports: 
      - "8080:8080"

  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretquery  
    ports: 
      - "3306:3306"

  web:
    #Uncomment line below if you want to build from Github source code
    #Otherwise it will pull pre-built images from Docker Hub
    #build: ./web
    container_name: web
    image: appdynamics/sample-app-web
    environment:
      - CONTROLLER_URL=peaks202002061058544.saas.appdynamics.com
      - CONTROLLER_PORT=443
      - CONTROLLER_ACCOUNT_NAME=peaks202002061058544
      - CONTROLLER_ACCESS_KEY=t84drcmx46cv
      - APP_ID=
    links:
      - rest
      - db
    ports:
      - "3000:3000"

#https://github.com/Appdynamics/SampleApp
#setup
#docker-compose -f ./docker-compose-appD-sampleApp.yml up -d
#docker exec -it rest install-appdynamics; docker exec rest start-all
#clean up
#docker-compose -f ./docker-compose-appD-sampleApp.yml down
#docker rmi -f appdynamics/sample-app-rest appdynamics/sample-app-web mysql